CREATE TABLE LOGIN (
	ID	VARCHAR2(30)	primary key,
	USERSETTINGCODE	NUMBER(38)	,
	PW	NUMBER(20)	NULL,
	EMAIL	VARCHAR2(30)	NULL,
	NAME	VARCHAR2(20)	NULL
);

insert into login values('k1ang1234',20501,1223,'aa@aaf.com','kangdonghyun');
drop table login
select * from login
CREATE TABLE BACKGROUND (
	BGCODE	NUMBER(38)	NOT NULL,
	WEATHER	VARCHAR2(20)	NULL
);

CREATE TABLE CLOCKUI (
	UICODE	NUMBER(38)	NOT NULL,
	TONE	VARCHAR2(20)	NULL
);

CREATE TABLE QUIZ (
	QUIZCODE	NUMBER(38)	NOT NULL,
	QUIZKINDS	VARCHAR2(20)	NULL
);

CREATE TABLE SETTING (
	USERSETTINGCODE	NUMBER(38)	NOT NULL unique,
	BGCODE	NUMBER(38)	NOT NULL,
	UICODE	NUMBER(38)	NOT NULL,
	QUIZCODE	NUMBER(38)	NOT NULL,
	TIMECODE	NUMBER(38)	NOT NULL
);
CREATE TABLE TIME (
	TIMECODE	NUMBER(38)	NOT NULL,
	STOPSOUND	NUMBER(38)	NULL,
	DAYREPEAT	VARCHAR2(20)	NULL,
	FONT	VARCHAR2(20)	NULL
);

ALTER TABLE LOGIN ADD CONSTRAINT PK_LOGIN PRIMARY KEY (
	ID,
	USERSETTINGCODE
);

ALTER TABLE BACKGROUND ADD CONSTRAINT PK_BACKGROUND PRIMARY KEY (
	BGCODE
);

ALTER TABLE CLOCKUI ADD CONSTRAINT PK_CLOCKUI PRIMARY KEY (
	UICODE
);

ALTER TABLE QUIZ ADD CONSTRAINT PK_QUIZ PRIMARY KEY (
	QUIZCODE
);

ALTER TABLE SETTING ADD CONSTRAINT PK_SETTING PRIMARY KEY (
	USERSETTINGCODE,
	BGCODE,
	UICODE,
	QUIZCODE,
	TIMECODE
);

ALTER TABLE TIME ADD CONSTRAINT PK_TIME PRIMARY KEY (
	TIMECODE
);



ALTER TABLE LOGIN ADD CONSTRAINT FK_SETTING_TO_LOGIN_1 FOREIGN KEY (
	USERSETTINGCODE
)

REFERENCES SETTING (
	USERSETTINGCODE
);

ALTER TABLE SETTING ADD CONSTRAINT FK_BACKGROUND_TO_SETTING_1 FOREIGN KEY (
	BGCODE
)
REFERENCES BACKGROUND (
	BGCODE
);

ALTER TABLE SETTING ADD CONSTRAINT FK_CLOCKUI_TO_SETTING_1 FOREIGN KEY (
	UICODE
)
REFERENCES CLOCKUI (
	UICODE
);

ALTER TABLE SETTING ADD CONSTRAINT FK_QUIZ_TO_SETTING_1 FOREIGN KEY (
	QUIZCODE
)
REFERENCES QUIZ (
	QUIZCODE
);

ALTER TABLE SETTING ADD CONSTRAINT FK_TIME_TO_SETTING_1 FOREIGN KEY (
	TIMECODE
)
REFERENCES TIME (
	TIMECODE
);

